name: cuid2
description: A dart implementaion of the secure, collision-resistant ids optimized for horizontal scaling and performance (v2).
version: 3.2.0
homepage: https://github.com/obsidiaHQ/cuid2
repository: https://github.com/obsidiaHQ/cuid2

environment:
  sdk: ">=2.14.0 <3.0.0"

executables: 
  cuid2:

dependencies:
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.0.0
